apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc-data
  namespace: repositories
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
  volumeName: gitea-pv-data
