apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: repository
spec:
  replicas: 1
  template:
    metadata:
      name: gitea
      labels:
        app:  gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:latest
        imagePullPolicy: IfNotPresent
        restartPolicy: Always

        ports:
        - containerPort: 22
        - containerPort: 3000

        volumeMounts:
        - mountPath: /data
          name: gitea-storage
          subPath: gitea/data

      volumes:
      - name: gitea-storage
        persistentVolumeClaim:
          claimName: k3s-repository-pvc

  selector:
    matchLabels:
      app: gitea