apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-root-pvc
  namespace: repositories
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
