apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: repository
spec:
  ports:
  - nodePort: 30020
    port: 22
    protocol: TCP
    targetPort: 22
    name: ssh-shell
  - nodePort: 30080
    port: 3000
    protocol: TCP
    targetPort: 3000
    name: http

  selector:
    app: gitea
  type: NodePort
