apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitea
  namespace: repositories
spec:
  rules:
  - host: gitea.192.168.2.140.nip.io
    http:
      paths:
      - backend:
          serviceName: gitea
          servicePort: http
        path: /
  tls:
  - hosts:
    - gitea.192.168.2.140.nip.io

#  The tls host needs to be converted to a variable or addressed through dns