apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: repositories
spec:
  ports:
  - name: http
    port: 3000
    targetPort: http
  selector:
    app: gitea
