apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-pvc-root
  namespace: repositories
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: gitea-pv-root
