apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k3s-repository-pvc
  namespace: repository
spec:
  accessModes: [ 'ReadWriteOnce', 'ReadWriteMany' ]
  resources:
    requests:
      storage: 1Ti
  storageClassName: ""
