apiVersion: v1
kind: Service
metadata:
  labels:
    app: registry
  name: registry
  namespace: repository
spec:
  ports:
  - nodePort:
    port: 5000
    protocol: TCP
    targetPort: 5000
    name: http

  selector:
    app: registry
  type: NodePort 