apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ 'ReadWriteOnce' ]
  nfs:
    path: /mnt/Gaia/k3s/monitoring
    server: 192.168.0.115
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: monitoring
    name: grafana-storage
