apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ 'ReadWriteOnce' ]
  nfs:
    path: /mnt/Gaia/k3s/monitoring/
    server: 192.168.0.115
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: monitoring
    name: prometheus-k8s-db-prometheus-k8s-0
