apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ 'ReadWriteMany' ]
  nfs:
    path: /mnt/Gaia/k3s/
    server: 192.168.2.83
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: communication
    name: prometheus-storage
