apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: [ 'ReadWriteOnce' ]
  nfs:
    path: /mnt/Gaia/k3s/
    server: 192.168.2.83
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/monitoring/prometheus"
  claimRef:
    namespace: monitoring
    name: prometheus-storage
