apiVersion: v1
kind: Namespace
metadata:
  name: communication
---
apiVersion: v1
kind: Namespace
metadata:
  name: openhab
---
apiVersion: v1
kind: Namespace
metadata:
  name: drupal

---
apiVersion: v1
kind: Namespace
metadata:
  name: repositories

# monitoring namesapce is added by cluster-monitoring playbook
