apiVersion: v1
kind: Namespace
metadata:
  name: communication
---
apiVersion: v1
kind: Namespace
metadata:
  name: home
---
apiVersion: v1
kind: Namespace
metadata:
  name: web

---
apiVersion: v1
kind: Namespace
metadata:
  name: repository

# monitoring namesapce is added by cluster-monitoring playbook
