apiVersion: v1
kind: PersistentVolume
metadata:
  name: mqtt-data-pv
spec:
  capacity:
    storage: 1Gi
  accessModes: [ 'ReadWriteOnce' ]
  nfs:
    path: /mnt/Gaia/k3s/communication/mosquitto-data
    server: 192.168.2.83
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: communication
    name: mqtt-data-pvc
